In [2]:
import numpy as np

# Definir el método de la secante con una tabla de resultados
def secante_tabla(fx, xa, tolera):
    dx = 4 * tolera  # Establecemos el tamaño inicial de dx
    xb = xa + dx  # Establecemos el valor inicial de xb
    tramo = dx
    tabla = []  # Lista para almacenar los resultados
    n_iter = 0  # Contador de iteraciones
    
    while tramo >= tolera:  # Mientras el tramo sea mayor que la tolerancia
        fa = fx(xa)
        fb = fx(xb)
        xc = xa - fa * (xb - xa) / (fb - fa)  # Fórmula de la secante
        tramo = abs(xc - xa)  # Calculamos el tramo (distancia entre xa y xc)
        
        # Añadimos los valores de la iteración a la tabla
        tabla.append([xa, xb, xc, tramo])
        
        # Actualizamos xa y xb para la siguiente iteración
        xb = xa
        xa = xc
        
        n_iter += 1  # Incrementamos el número de iteraciones

    # Convertir la lista de resultados a un array de numpy
    tabla = np.array(tabla)
    return tabla

# Definir la función f(x)
fx = lambda x: 230 * x**4 + 18 * x**3 + 9 * x**2 - 221 * x - 9

# Parámetros iniciales
xa = 1
tolera = 10**(-6)

# Llamamos a la función de la secante
tabla = secante_tabla(fx, xa, tolera)

# Obtenemos la raíz en la última iteración
raiz = tabla[-1, 2]

# Configurar la salida de numpy para que imprima con cuatro decimales
np.set_printoptions(precision=4)

# Mostrar los resultados
print("Tabla de resultados:")
print(tabla)  # Mostrar la tabla completa de iteraciones
print(f"Raíz estimada: {raiz}")


Tabla de resultados:
[[1.0000e+00 1.0000e+00 9.6498e-01 3.5019e-02]
 [9.6498e-01 1.0000e+00 9.6258e-01 2.3973e-03]
 [9.6258e-01 9.6498e-01 9.6240e-01 1.8417e-04]
 [9.6240e-01 9.6258e-01 9.6240e-01 9.5680e-07]]
Raíz estimada: 0.9623984191065308
